version: '1'
servixes:
  nginx:
    image: nignx
    volumes:
      - /usr/share/nginx/html
    ports:
      - "80:50000"
"""
docker run -d --rm \
  -p 50000:80 \
  -v $(pwd)/index.html:/usr/share/nginx/html/index.html \
  nginx
"""